### ISSUE TITLE
feat: ipv4-to-emoji

### ISSUE THREAD

**Issue by lveneris** [IJMacD/emoji-to-ipv4#1]
If we can do it one way, surely we can do it the other. What do you think? I think it'd be a pretty neat idea if we could make this a bilateral operation in which emojis can be converted to ipv4 and vice versa.

I'd be more than willing to help or open a PR for this.

**Comment by IJMacD** [comment]
Hi Tyler,

Thanks for your interest. I've now added the reverse so IPv4 addresses can be converted into text.  

You can always convert an address into four codepoints between U+0 and U+FF although some might not be printable (i.e. the first 32 of them and the 32 starting at U+80).

Occasionally the four bytes make up a valid UTF-8 sequence as well.

I've included both these outputs (if valid) in the app.

**Comment by IJMacD** [comment]
Implemented in 341ac30

**Comment by lveneris** [comment]
> Thanks for your interest. I've now added the reverse so IPv4 addresses
> can be converted into text.

That was fast. Thank you for your time and efforts :)
